import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  // NOTE: this REPLACES the defaults rather than extending them, so every
  // generated directory must be listed here explicitly — anything missing gets
  // linted as source. Keep in sync with .gitignore (.remember/** is an
  // exception: it's ignored via the user's global gitignore, not this repo's).
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Cloudflare Workers adapter and the local Supabase CLI:
    ".open-next/**",
    ".wrangler/**",
    "supabase/.temp/**",
    ".remember/**",
    ".superpowers/**",
  ]),
]);

export default eslintConfig;
